/**
 * metaPixel.ts — Meta Pixel + Conversions API Infrastructure
 *
 * ARCHITECTURE:
 * 1. Browser-side fbq() fires immediately (low latency)
 * 2. Server-side CAPI fires from Supabase edge function (survives iOS/Safari blocking)
 * 3. Both share event_id for deduplication — Meta counts each event once
 *
 * CONVERSION FUNNEL (Facebook Ad Manager optimization):
 *   PageView          → automatic on load
 *   ViewContent       → user engages with tool (step 2+)
 *   Lead              → phone/email captured at lead gate
 *   CompleteRegistration → OTP verified, full report unlocked
 *   Schedule          → contractor match requested (highest value)
 *
 * CUSTOM EVENTS (retargeting audiences):
 *   wm_shadow_created          → step 2 complete (abandonment seed)
 *   wm_county_identified       → county selected (geo-targeted retargeting)
 *   wm_flow_routed             → step 4 answered
 *   wm_grade_revealed          → grade shown
 *   wm_grade_critical          → D/F grade (contractor match intent)
 *   wm_otp_verified            → phone verified
 *   wm_contractor_match_requested → final CTA
 *   wm_report_unlocked         → full report revealed
 *   wm_upload_started          → quote upload initiated
 */

import { v4 as uuidv4 } from "uuid";
import { getLeadId } from "./useLeadId";
import { getUtmData } from "./useUtmCapture";

// ── PIXEL ID ─────────────────────────────────────────────────────────────────
// Set via env var or hardcode for production
const PIXEL_ID = import.meta.env.VITE_META_PIXEL_ID || "";

// ── SHA-256 HASHER (Meta CAPI spec requires lowercase trimmed hashing) ───────

async function sha256(text: string): Promise<string> {
  const buffer = await crypto.subtle.digest(
    "SHA-256",
    new TextEncoder().encode(text.toLowerCase().trim())
  );
  return Array.from(new Uint8Array(buffer))
    .map((b) => b.toString(16).padStart(2, "0"))
    .join("");
}

// ── COOKIE HELPERS ───────────────────────────────────────────────────────────

function getCookie(name: string): string | null {
  if (typeof document === "undefined") return null;
  const match = document.cookie.match(new RegExp(`(^| )${name}=([^;]+)`));
  return match ? decodeURIComponent(match[2]) : null;
}

function setCookie(name: string, value: string, days: number) {
  if (typeof document === "undefined") return;
  const expires = new Date(Date.now() + days * 864e5).toUTCString();
  document.cookie = `${name}=${encodeURIComponent(value)};expires=${expires};path=/;SameSite=Lax`;
}

// ── FBC COOKIE (Facebook Click ID) ──────────────────────────────────────────
// Format: fb.1.{timestamp}.{fbclid}
// Must be set from URL param on landing, persisted for 90 days

export function captureFbc(): string | null {
  if (typeof window === "undefined") return null;

  // Check if already set
  const existing = getCookie("_fbc");
  if (existing) return existing;

  // Capture from URL
  const params = new URLSearchParams(window.location.search);
  const fbclid = params.get("fbclid");
  if (fbclid) {
    const fbc = `fb.1.${Date.now()}.${fbclid}`;
    setCookie("_fbc", fbc, 90);
    return fbc;
  }

  return null;
}

// ── FBP COOKIE (Facebook Browser ID) ────────────────────────────────────────
// Format: fb.1.{timestamp}.{random}
// Auto-generated by pixel, but we ensure it exists for CAPI

export function getFbp(): string | null {
  return getCookie("_fbp");
}

// ── GENERATE EVENT ID ────────────────────────────────────────────────────────

export function generateEventId(prefix: string = "wm"): string {
  return `${prefix}_${Date.now()}_${uuidv4().slice(0, 8)}`;
}

// ── BROWSER PIXEL FIRE ──────────────────────────────────────────────────────

function fbqTrack(
  eventName: string,
  params: Record<string, unknown> = {},
  eventId: string
) {
  if (typeof window === "undefined") return;
  const fbq = (window as any).fbq;
  if (!fbq) return;

  // Standard events use 'track', custom events use 'trackCustom'
  const standardEvents = [
    "PageView", "ViewContent", "Lead", "CompleteRegistration",
    "Purchase", "Schedule", "AddToCart", "InitiateCheckout",
  ];

  if (standardEvents.includes(eventName)) {
    fbq("track", eventName, params, { eventID: eventId });
  } else {
    fbq("trackCustom", eventName, params, { eventID: eventId });
  }
}

// ── SERVER-SIDE CAPI FIRE ───────────────────────────────────────────────────

interface CAPIPayload {
  event_name: string;
  event_id: string;
  event_time: number;
  event_source_url: string;
  action_source: "website";
  client_slug?: string;
  user_data: {
    em?: string;        // hashed email
    ph?: string;        // hashed phone
    fbc?: string;       // _fbc cookie
    fbp?: string;       // _fbp cookie
    external_id?: string; // lead UUID
    client_ip_address?: string;
    client_user_agent?: string;
    fn?: string;        // hashed first name
    st?: string;        // hashed state (always "florida")
    country?: string;   // hashed country (always "us")
  };
  custom_data?: Record<string, unknown>;
}

async function fireCAPI(payload: CAPIPayload) {
  const capiUrl = import.meta.env.VITE_SUPABASE_URL
    ? `${import.meta.env.VITE_SUPABASE_URL}/functions/v1/capi-event`
    : null;

  if (!capiUrl) return;

  try {
    await fetch(capiUrl, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || ""}`,
      },
      body: JSON.stringify(payload),
    });
  } catch {
    // Silent fail — CAPI is supplementary, never blocking
  }
}

// ── MAIN EVENT DISPATCHER ───────────────────────────────────────────────────

interface TrackEventOptions {
  eventName: string;
  standardEventName?: string;
  params?: Record<string, unknown>;
  email?: string;
  phone?: string;
  firstName?: string;
  value?: number;
  currency?: string;
  clientSlug?: string;
}

export async function trackConversion(options: TrackEventOptions): Promise<string> {
  const eventId = generateEventId();
  const utmData = getUtmData();
  const leadId = getLeadId();

  // Clean params — strip PII before browser pixel
  const browserParams: Record<string, unknown> = {
    ...options.params,
    content_name: "Impact Window Quote Analysis",
    content_category: "Home Improvement",
  };
  delete browserParams.email;
  delete browserParams.phone;

  // Add UTM data to params
  if (utmData.utm_source) browserParams.utm_source = utmData.utm_source;
  if (utmData.utm_campaign) browserParams.utm_campaign = utmData.utm_campaign;

  // 1. Browser pixel (immediate)
  const trackName = options.standardEventName || options.eventName;
  fbqTrack(trackName, browserParams, eventId);

  // Also fire custom event if standard event was used
  if (options.standardEventName && options.standardEventName !== options.eventName) {
    fbqTrack(options.eventName, browserParams, `${eventId}_custom`);
  }

  // 2. Server-side CAPI (async, survives iOS blocking)
  const hashedEmail = options.email ? await sha256(options.email) : undefined;
  const hashedPhone = options.phone
    ? await sha256(options.phone.replace(/\D/g, ""))
    : undefined;
  const hashedFirstName = options.firstName ? await sha256(options.firstName) : undefined;

  const capiPayload: CAPIPayload = {
    event_name: trackName,
    event_id: eventId,
    event_time: Math.floor(Date.now() / 1000),
    event_source_url: window.location.href,
    action_source: "website",
    user_data: {
      em: hashedEmail,
      ph: hashedPhone,
      fn: hashedFirstName,
      fbc: captureFbc() || undefined,
      fbp: getFbp() || undefined,
      external_id: leadId || undefined,
      client_user_agent: navigator.userAgent,
      st: await sha256("florida"),
      country: await sha256("us"),
    },
    custom_data: {
      ...browserParams,
      lead_id: leadId,
      value: options.value,
      currency: options.currency || "USD",
    },
  };

  await fireCAPI(capiPayload);

  // 3. Push to dataLayer for GTM
  if (typeof window !== "undefined" && (window as any).dataLayer) {
    (window as any).dataLayer.push({
      event: options.eventName,
      event_id: eventId,
      lead_id: leadId,
      ...browserParams,
    });
  }

  return eventId;
}

// ── NAMED CONVERSION EVENTS ─────────────────────────────────────────────────

export const metaConversions = {
  /** Page view — fires on initial load */
  pageView: () =>
    trackConversion({
      eventName: "wm_page_view",
      standardEventName: "PageView",
    }),

  /** ViewContent — user engages with tool (step 2+) */
  viewContent: (params: { county?: string; step?: number }) =>
    trackConversion({
      eventName: "wm_shadow_created",
      standardEventName: "ViewContent",
      params: {
        content_ids: [params.county || "FL"],
        ...params,
      },
    }),

  /** County identified — enables geo-targeted retargeting */
  countyIdentified: (county: string) =>
    trackConversion({
      eventName: "wm_county_identified",
      params: { county },
    }),

  /** Flow routed — step 4 answered */
  flowRouted: (params: { county?: string; flow: string; quoteRange?: string }) =>
    trackConversion({
      eventName: "wm_flow_routed",
      params,
    }),

  /** Upload started — quote upload initiated */
  uploadStarted: (params: { county?: string }) =>
    trackConversion({
      eventName: "wm_upload_started",
      standardEventName: "AddToCart",
      params,
    }),

  /** Lead captured — phone/email submitted */
  leadCaptured: (params: {
    county?: string;
    flow?: string;
    email?: string;
    phone?: string;
    firstName?: string;
  }) =>
    trackConversion({
      eventName: "wm_lead_submitted",
      standardEventName: "Lead",
      email: params.email,
      phone: params.phone,
      firstName: params.firstName,
      params: {
        county: params.county,
        flow: params.flow,
        content_name: "Impact Window Lead",
        content_category:
          params.flow === "C"
            ? "Pre-Quote High Urgency"
            : params.flow === "A"
              ? "Has Written Quote"
              : "Research Phase",
      },
    }),

  /** OTP verified — phone confirmed, full report unlocked */
  otpVerified: (params: { county?: string; flow?: string; phone?: string; clientSlug?: string }) =>
    trackConversion({
      eventName: "wm_otp_verified",
      standardEventName: "CompleteRegistration",
      phone: params.phone,
      clientSlug: params.clientSlug,
      params: {
        county: params.county,
        flow: params.flow,
      },
    }),

  /** Report unlocked — full findings revealed */
  reportUnlocked: (params: { county?: string; grade?: string }) =>
    trackConversion({
      eventName: "wm_report_unlocked",
      params,
    }),

  /** Grade revealed — scan result shown */
  gradeRevealed: (params: { grade: string; dollarDelta?: number; county?: string }) =>
    trackConversion({
      eventName: "wm_grade_revealed",
      params,
    }),

  /** Grade critical — D/F grade, highest contractor match intent */
  gradeCritical: (params: { grade: string; county?: string }) =>
    trackConversion({
      eventName: "wm_grade_critical",
      params,
    }),

  /** Contractor match requested — final CTA, highest value */
  contractorMatchRequested: (params: { county?: string; grade?: string }) =>
    trackConversion({
      eventName: "wm_contractor_match_requested",
      standardEventName: "Schedule",
      params,
      value: 0,
    }),
};

// ── PIXEL INITIALIZATION ────────────────────────────────────────────────────

export function initMetaPixel() {
  if (typeof window === "undefined") return;
  if (!PIXEL_ID) {
    console.warn("[MetaPixel] No VITE_META_PIXEL_ID set — pixel disabled");
    return;
  }

  // Don't double-init
  if ((window as any).fbq) return;

  // Standard Meta Pixel base code
  const f: any = (window as any);
  const n: any = (f.fbq = function (...args: any[]) {
    n.callMethod ? n.callMethod.apply(n, args) : n.queue.push(args);
  });
  if (!f._fbq) f._fbq = n;
  n.push = n;
  n.loaded = true;
  n.version = "2.0";
  n.queue = [];

  // Load pixel script
  const script = document.createElement("script");
  script.async = true;
  script.src = "https://connect.facebook.net/en_US/fbevents.js";
  document.head.appendChild(script);

  // Init with pixel ID
  (window as any).fbq("init", PIXEL_ID, {
    external_id: getLeadId(),
  });

  // Fire PageView
  (window as any).fbq("track", "PageView");

  // Capture fbc from URL
  captureFbc();
}
