export default function Disclaimer() {
  return (
    <main className="min-h-screen bg-background text-foreground">
      <section className="mx-auto max-w-4xl px-6 py-16 md:px-8 md:py-24">
        <div className="mb-10">
          <p className="mb-3 text-xs font-semibold uppercase tracking-[0.22em] text-muted-foreground">
            Disclaimer
          </p>
          <h1 className="text-3xl font-semibold tracking-tight md:text-5xl">
            Legal Disclaimer
          </h1>
        </div>

        <article className="prose prose-invert max-w-none text-base leading-7 text-foreground/90">
          <p>
            WindowMan.PRO provides AI-driven educational estimates, quote review
            assistance, and informational analysis only.
          </p>

          <p>
            The content, findings, scores, benchmarks, flags, recommendations, and
            outputs generated by the platform are not legally binding and should
            not be interpreted as legal advice, financial advice, insurance
            advice, tax advice, public adjusting advice, contractor advice, or
            structural engineering advice.
          </p>

          <p>
            Any quote analysis presented by WindowMan.PRO is intended to help
            homeowners ask better questions and make more informed decisions. It
            does not replace review by a licensed attorney, engineer, inspector,
            accountant, contractor, or other qualified professional.
          </p>

          <p>
            WindowMan.PRO does not guarantee pricing, code compliance, permitting
            outcomes, product suitability, installation quality, savings, or
            project performance. Real-world conditions, local regulations,
            contract terms, and field measurements may materially affect actual
            results.
          </p>

          <p>
            By using this platform, you acknowledge that you are relying on the
            service at your own discretion and that final purchase, contract, and
            construction decisions remain your responsibility.
          </p>
        </article>
      </section>
    </main>
  );
}
