import { AlertTriangle, FileText, Users } from "lucide-react";
import { useNavigate } from "react-router-dom";
import StickyCTAFooter from "@/components/StickyCTAFooter";

export default function Terms() {
  const navigate = useNavigate();
  return (
    <main
      className="relative min-h-screen overflow-hidden pb-32"
      style={{
        background:
          "linear-gradient(170deg, #dce8f4 0%, #e4edf6 30%, #eaeff8 60%, #dde6f2 100%)",
      }}
    >
      <section className="mx-auto max-w-4xl px-4 py-16 md:px-8 md:py-24">
        <div className="mb-10">
          <p className="mb-3 text-xs font-semibold uppercase tracking-[0.22em] text-gray-500">
            Terms of Service
          </p>
          <h1 className="text-3xl font-semibold tracking-tight text-gray-900 md:text-5xl">
            Terms of Service
          </h1>
          <p className="mt-4 text-sm leading-6 text-gray-500">
            Last updated: April 14, 2026
          </p>
        </div>

        {/* Important Disclaimer Box */}
        <div className="mb-10 rounded-2xl border border-amber-200/60 bg-amber-50/50 p-6 shadow-sm backdrop-blur-sm">
          <div className="flex items-start gap-4">
            <div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-full bg-amber-100">
              <AlertTriangle className="h-6 w-6 text-amber-600" />
            </div>
            <div>
              <h2 className="mb-2 text-lg font-semibold text-gray-900">
                Important Disclaimer
              </h2>
              <p className="text-sm leading-6 text-gray-600">
                The "Truth Report" generated by WindowMan.PRO is an{" "}
                <strong className="text-gray-900">
                  AI-generated benchmark and negotiation tool
                </strong>
                . It is{" "}
                <strong className="text-gray-900">
                  not a legally binding engineering, financial, or inspection
                  document
                </strong>
                . Final pricing, scope, and specifications are subject to
                contractor site visits, permit requirements, and actual field
                conditions.
              </p>
            </div>
          </div>
        </div>

        {/* Key Points */}
        <div className="mb-10 grid gap-4 md:grid-cols-3">
          <div className="flex items-center gap-3 rounded-xl border border-slate-200/60 bg-white/70 p-4 shadow-sm backdrop-blur-sm">
            <FileText className="h-5 w-5 text-blue-600" />
            <span className="text-sm font-medium text-gray-700">
              Educational Analysis Only
            </span>
          </div>
          <div className="flex items-center gap-3 rounded-xl border border-slate-200/60 bg-white/70 p-4 shadow-sm backdrop-blur-sm">
            <Users className="h-5 w-5 text-blue-600" />
            <span className="text-sm font-medium text-gray-700">
              Not Professional Advice
            </span>
          </div>
          <div className="flex items-center gap-3 rounded-xl border border-slate-200/60 bg-white/70 p-4 shadow-sm backdrop-blur-sm">
            <AlertTriangle className="h-5 w-5 text-blue-600" />
            <span className="text-sm font-medium text-gray-700">
              Site Visit Required for Final Price
            </span>
          </div>
        </div>

        {/* Terms Content */}
        <div className="rounded-2xl border border-slate-200/60 bg-white/70 p-6 shadow-sm backdrop-blur-sm md:p-8">
          <article className="prose prose-slate max-w-none text-base leading-7 text-gray-600">
            <p>
              These Terms of Service ("Terms") govern your access to and use of
              WindowMan.PRO. By using the platform, you agree to these Terms.
            </p>

            <h2 className="mt-8 text-xl font-semibold text-gray-900">
              Use of the Service
            </h2>
            <p>
              WindowMan.PRO provides AI-assisted quote analysis, educational
              summaries, and related homeowner decision-support tools for impact
              window and door projects in South Florida. You agree to use the
              service only for lawful purposes and in a manner that does not
              interfere with the operation of the platform.
            </p>

            <h2 className="mt-8 text-xl font-semibold text-gray-900">
              Truth Report Disclaimer
            </h2>
            <div className="rounded-lg border-l-4 border-amber-500 bg-amber-50 py-3 pl-4 pr-3">
              <p className="mb-0 text-sm font-medium text-gray-700">
                <strong>The "Truth Report" is an AI-generated benchmark</strong>{" "}
                intended to help homeowners better understand their quote and
                prepare for negotiations. It is{" "}
                <strong>
                  not a legally binding engineering document, financial advice,
                  inspection report, or licensed professional opinion
                </strong>
                .
              </p>
              <p className="mt-2 mb-0 text-sm text-gray-600">
                Final pricing, scope, product specifications, and installation
                details are subject to:
              </p>
              <ul className="mt-1 mb-0 list-disc space-y-0.5 pl-5 text-sm text-gray-600">
                <li>Contractor site visits and field measurements</li>
                <li>Local permit requirements and code compliance</li>
                <li>Product availability and manufacturer specifications</li>
                <li>Actual structural conditions at your property</li>
              </ul>
            </div>

            <h2 className="mt-8 text-xl font-semibold text-gray-900">
              No Professional Advice
            </h2>
            <p>
              The platform does not provide legal, engineering, accounting,
              insurance, financial, public adjusting, or other licensed
              professional advice. Any output should be reviewed with
              appropriate licensed professionals where needed. The Truth Report
              should not be used as a substitute for professional inspections,
              engineering assessments, or legal counsel.
            </p>

            <h2 className="mt-8 text-xl font-semibold text-gray-900">
              User Content
            </h2>
            <p>
              You retain ownership of the content and documents you upload. By
              submitting content, you grant us a limited right to process,
              analyze, store, and display that content as necessary to operate
              the service and generate your Truth Report.
            </p>

            <h2 className="mt-8 text-xl font-semibold text-gray-900">
              Accuracy and Availability
            </h2>
            <p>
              We aim to provide useful and reliable analysis, but we do not
              warrant that the platform will always be uninterrupted, error-free,
              or fully complete. Outputs may contain inaccuracies, omissions, or
              AI-generated estimates that do not reflect actual market conditions
              or contractor pricing.
            </p>

            <h2 className="mt-8 text-xl font-semibold text-gray-900">
              Contractor Matching
            </h2>
            <p>
              In some cases, we may offer introductions to vetted contractors.
              Any decision to engage a contractor is solely yours. WindowMan.PRO
              is not a party to any contract between you and a contractor unless
              explicitly stated otherwise. We receive a referral fee if you
              choose to work with one of our vetted partners, but this does not
              affect the accuracy or integrity of your Truth Report.
            </p>

            <h2 className="mt-8 text-xl font-semibold text-gray-900">
              Prohibited Conduct
            </h2>
            <ul className="list-disc space-y-1 pl-6">
              <li>Uploading unlawful, fraudulent, or misleading content.</li>
              <li>
                Attempting to reverse engineer, disrupt, or exploit the
                platform.
              </li>
              <li>
                Using the service to violate privacy, contract, or other rights.
              </li>
              <li>
                Misrepresenting the Truth Report as an official engineering or
                legal document.
              </li>
            </ul>

            <h2 className="mt-8 text-xl font-semibold text-gray-900">
              Limitation of Liability
            </h2>
            <p>
              To the maximum extent permitted by law, WindowMan.PRO and its
              affiliates shall not be liable for any indirect, incidental,
              special, consequential, or punitive damages, or for any loss
              arising from your use of or reliance on the service, including but
              not limited to decisions made based on Truth Report analysis.
            </p>

            <h2 className="mt-8 text-xl font-semibold text-gray-900">
              Termination
            </h2>
            <p>
              We reserve the right to suspend or terminate access to the service
              at any time if we believe these Terms have been violated or the
              platform is being misused.
            </p>

            <h2 className="mt-8 text-xl font-semibold text-gray-900">
              Changes to the Terms
            </h2>
            <p>
              We may revise these Terms from time to time. Continued use of the
              platform after updated Terms are posted constitutes acceptance of
              the revised Terms.
            </p>

            <h2 className="mt-8 text-xl font-semibold text-gray-900">
              Contact
            </h2>
            <p>
              Questions about these Terms may be directed to{" "}
              <a
                href="mailto:support@windowman.pro"
                className="font-medium text-blue-600 hover:text-blue-700"
              >
                support@windowman.pro
              </a>
              .
            </p>
          </article>
        </div>
      </section>
      <StickyCTAFooter
        isVisible={true}
        conversionType={null}
        onScanClick={() => navigate("/?action=scan")}
        onDemoClick={() => navigate("/?action=demo")}
        onPostConversionClick={() => { window.location.href = "tel:+15614685571"; }}
      />
    </main>
  );
}
