import type { ExtractionResult } from "./scoring.ts";

export const BASE_GOOD_QUOTE: ExtractionResult = {
  document_type: "impact_window_quote",
  is_window_door_related: true,
  confidence: 0.92,
  page_count: 4,
  contractor_name: "Example Impact Windows",
  opening_count: 8,
  total_quoted_price: 16800,
  hvhz_zone: true,
  cancellation_policy: "3-day right to cancel included",
  terms_conditions_present: true,
  subject_to_remeasure_present: false,
  final_payment_before_inspection: false,
  payment_schedule_text: "30/40/30 schedule after milestones",
  generic_product_description_present: false,
  line_items: [
    {
      description: "Living room single hung impact window",
      quantity: 1,
      unit_price: 1400,
      total_price: 1400,
      brand: "PGT",
      series: "WinGuard",
      dp_rating: "DP 50",
      noa_number: "FL12345",
      dimensions: "36x60",
      opening_location: "Living Room",
      opening_tag: "W1",
      product_assignment_text: "PGT WinGuard SH",
      glass_package_text: "Insulated laminated Low-E Argon",
      glass_makeup_type: "insulated_laminated",
      glass_low_e_present: true,
      glass_argon_present: true,
      glass_tint_text: "clear",
      glass_spec_complete: true,
    },
    {
      description: "Kitchen single hung impact window",
      quantity: 1,
      unit_price: 1400,
      total_price: 1400,
      brand: "PGT",
      series: "WinGuard",
      dp_rating: "DP 50",
      noa_number: "FL12345",
      dimensions: "36x60",
      opening_location: "Kitchen",
      opening_tag: "W2",
      product_assignment_text: "PGT WinGuard SH",
      glass_package_text: "Insulated laminated Low-E Argon",
      glass_makeup_type: "insulated_laminated",
      glass_low_e_present: true,
      glass_argon_present: true,
      glass_tint_text: "clear",
      glass_spec_complete: true,
    },
  ],
  permits: { included: true, responsible_party: "contractor", details: "permit included" },
  installation: { scope_detail: "remove/replace/flash/seal", disposal_included: true, accessories_mentioned: true },
  warranty: { labor_years: 5, manufacturer_years: 20, transferable: true, details: "written warranty included" },

  // ── Area 1: Glass ──────────────────────────────────────────────────────────
  opening_level_glass_specs_present: true,
  blanket_glass_language_present: false,
  mixed_glass_package_visibility: false,

  // ── Area 2: Scope ──────────────────────────────────────────────────────────
  opening_schedule_present: true,
  opening_schedule_room_labels_present: true,
  opening_schedule_dimensions_complete: true,
  opening_schedule_product_assignments_present: true,
  bulk_scope_blob_present: false,

  // ── Area 3: Legal / Fine Print ─────────────────────────────────────────────
  written_change_order_required: true,
  homeowner_approval_required_for_change_orders: true,
  unilateral_price_adjustment_allowed: false,
  substrate_condition_clause_present: false,
  rot_unit_pricing_present: true,
  buck_replacement_unit_pricing_present: true,
  remeasure_price_adjustment_cap_present: true,

  // ── Area 4: Install Method ─────────────────────────────────────────────────
  anchoring_method_text: "Tapcon anchors per manufacturer spec",
  anchor_spacing_specified: true,
  fastener_type_specified: true,
  waterproofing_method_text: "sealant + flashing tape",
  sealant_specified: true,
  buck_treatment_method_text: "buck prep and seal",
  manufacturer_install_compliance_stated: true,
  code_compliance_install_statement_present: true,

  // ── Area 5: Warranty Execution ─────────────────────────────────────────────
  warranty_execution_details_present: true,
  warranty_service_provider_type: "contractor",
  warranty_service_provider_name: "Example Impact Windows",
  leak_callback_sla_days: 7,
  labor_service_sla_days: 5,
  callback_process_text: "Call main office, technician dispatched within 72 hours",
  post_install_stucco_excluded: false,
  post_install_paint_excluded: false,
  water_intrusion_damage_excluded: false,

  // ── Scope gap / trust fields ───────────────────────────────────────────────
  wall_repair_scope: "Stucco patch and interior touch-up included",
  stucco_repair_included: true,
  drywall_repair_included: true,
  paint_touchup_included: true,
  debris_removal_included: true,
  engineering_mentioned: true,
  engineering_fees_included: true,
  permit_fees_itemized: true,
  insurance_proof_mentioned: true,
  licensing_proof_mentioned: true,
  completion_timeline_text: "Install within 6-8 weeks after permit approval",
  lead_paint_disclosure_present: true,
};
