// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wkrcyxcnzhwjtdpmfpaf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndrcmN5eGNuemh3anRkcG1mcGFmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM3MTIxMDksImV4cCI6MjA4OTI4ODEwOX0._5MdqzJgBCDaGNvfqPbbrrDxAhM0Th4E9CMa6YL0aww";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});